### ISSUE TITLE
Can't get cmis:contentStreamLength

### ISSUE THREAD

**Issue by djiouls** [fvettore/php-alf-cmis-api#2]

**Comment by fvettore** [comment]
Please submit a detailed description of the issue

**Comment by djiouls** [comment]
If i do for exemple:
$folderAlf= new CMISalfObject($repoUrl,$username,$password,null,null,$pathAlf);
$folderAlf->listContent();
foreach($folderAlf->containedObjects as $obj){
$nomfic=$obj->properties['cmis:name'];
$datemodiffic=$obj->properties['cmis:lastModificationDate'];
$taillefic=$obj->properties['cmis:contentStreamLength'];
$descriptionfic=$obj->properties['cmis:description'];
}
I get everything but $obj->properties['cmis:contentStreamLength']

**Comment by fvettore** [comment]
Object Properties are reported as exposed by CMIS.
For example:
Array
(
    [cmis:versionSeriesCheckedOutBy] => 
    [cmis:versionLabel] => 1.0
    [cmis:lastModifiedBy] => admin
    [cmis:createdBy] => admin
    [cmis:name] => cartucce stylus pro3880.ods
    [cmis:contentStreamMimeType] => application/vnd.oasis.opendocument.spreadsheet
    [cmis:changeToken] => 
    [cmis:checkinComment] => 
    [cmis:description] => 
    [cmis:contentStreamFileName] => cartucce stylus pro3880.ods
    [cmis:objectTypeId] => cmis:document
    [cmis:versionSeriesCheckedOutId] => 
    [cmis:versionSeriesId] => workspace://SpacesStore/27cee3fb-a9ee-456c-9b2d-e2910f193233
    [alfcmis:nodeRef] => workspace://SpacesStore/27cee3fb-a9ee-456c-9b2d-e2910f193233
    [cmis:contentStreamId] => store://2015/11/20/10/50/89a930b8-bd9e-4f90-afc4-db9681cb475c.bin
    [cmis:objectId] => workspace://SpacesStore/27cee3fb-a9ee-456c-9b2d-e2910f193233;1.0
    [cmis:baseTypeId] => cmis:document
    [cmis:creationDate] => 2015-11-20T10:50:13.603+01:00
    [cmis:lastModificationDate] => 2015-11-20T16:08:46.839+01:00
    [cmis:isPrivateWorkingCopy] => 
    [cmis:isLatestVersion] => true
    [cmis:isVersionSeriesCheckedOut] => false
    [cmis:isLatestMajorVersion] => true
    [cmis:isImmutable] => false
    [cmis:isMajorVersion] => true
)

You can se the obyect has no cmis:contentStreamLength.
It is not an issue of the code.
